_target_: models.MAMLModel

cfg: 
  nway: ${datamodule.nway}
  num_inner_steps: 1
  use_lr_scheduler: False

  net:
    _target_: models.components.SimpleConvNet
    num_classes: ${datamodule.nway}
    kernel_size: 3
    hidden_channel: 32

  outer_optimizer:
    _target_: torch.optim.Adam
    _partial_: true
    lr: 0.001
    weight_decay: 0.0

  inner_optimizer:
    _target_: torch.optim.SGD
    _partial_: true
    lr: 0.01

  scheduler:
    _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
    _partial_: true
    mode: min
    factor: 0.1
    patience: 10