# https://neptune.ai

neptune:
  _target_: pytorch_lightning.loggers.neptune.NeptuneLogger
  api_key: "${oc.env:NEPTUNE_API_TOKEN}" # api key is loaded from environment variable
  project: "username/Few-Shot-Classification-on-Omniglot-Dataset"
  name: "Few-Shot-Classification-on-Omniglot-Dataset"
  log_model_checkpoints: True
  prefix: ""
